name: Deploy Vite React

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create TAR package
        run: |
          TS=$(date +%s)
          TAR="dist_$TS.tar.gz"
          tar -czf "$TAR" -C dist .
          echo "TAR=$TAR" >> "$GITHUB_ENV"

      - name: Setup SSH (Private key inline for testing)
        run: |
          mkdir -p ~/.ssh

          cat > ~/.ssh/id_ed25519 << 'EOF'
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACA0D/xvV+FUvQ7aSueYx49UBx+K6/VMbfcUARV+s58u2wAAAJCi+7ipovu4
qQAAAAtzc2gtZWQyNTUxOQAAACA0D/xvV+FUvQ7aSueYx49UBx+K6/VMbfcUARV+s58u2w
AAAEBEFWjWcQvRMbcmezJSN1CKwu7fqtsc56A6FZjGnwV/kjQP/G9X4VS9DtpK55jHj1QH
H4rr9Uxt9xQBFX6zny7bAAAADWdpdGh1Yi1kZXBsb3k=
-----END OPENSSH PRIVATE KEY-----
EOF

          chmod 600 ~/.ssh/id_ed25519

          # Add Host keys
          ssh-keyscan -T 5 -H "${{ secrets.JUMP_HOST }}" >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan -T 5 -H "${{ secrets.TARGET_HOST }}" >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Deploy to server via ProxyJump
        run: |
          echo "‚ö° Starting Deploy..."

          TS=$(date +%s)
          TMP="/home/${{ secrets.TARGET_USER }}/deploy_tmp/$TS"

          echo "üìÅ TMP folder: $TMP"

          # Create folder in VM
          ssh -o StrictHostKeyChecking=no \
              -J "${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }}" \
              "${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}" \
              "mkdir -p $TMP"

          # Upload TAR
          scp -o StrictHostKeyChecking=no \
              -o ProxyJump="${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }}" \
              "${{ env.TAR }}" \
              "${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}:$TMP/"

          # Extract TAR
          ssh -o StrictHostKeyChecking=no \
              -J "${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }}" \
              "${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}" \
              "tar -xzf $TMP/${{ env.TAR }} -C $TMP && rm $TMP/${{ env.TAR }}"

          # Run deploy script
          ssh -o StrictHostKeyChecking=no \
              -J "${{ secrets.JUMP_USER }}@${{ secrets.JUMP_HOST }}" \
              "${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }}" \
              "bash /home/${{ secrets.TARGET_USER }}/deploy_swap.sh $TMP"
